FROM nvidia/cuda:12.2.0-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    python3 \
    python3-pip \
    python3-venv \
    git \
    curl \
    wget \
    sudo \
    vim \
    && apt clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["python3", "--version"]
